@startuml

enum HoraExtra{
DIURNA
NOCTURNA
DOMINICAL
FESTIVO
}

enum DeduccionSalarial{
SALUD
PENSION
ARL
}

enum Cargo{
EMPLEADO
ADMIN
OWNER
}

class Registro{
- LocalDate fechaRegistro
- String descripcion
}

class Nomina{
-int montoPagado
-LocalDate fechaPago
-int montoBruto
-String descripcion
-int horasTrabajadas
-Empleado e
-List <Registro> registros
}

class Empleado{
-int sueldoBase
-int id
-String nombreCompleto
-String cedula
-Cargo cargo
-List<Nomina> nominas
}

class GestorNomina{
-List<Empleado>empleados
}



@enduml